lang: zh
title: Doom
logoText: Doom
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
  references:
    v1alpha1.CodeQualityBranch: /apis/references/CodeQualityBranch#CodeQualityBranch
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml
reference:
  - sources:
      - name: ref
        path: docs/zh/usage/configuration.md#reference
sidebar:
  collapsed: false
editRepoBaseUrl: alauda/doom/tree/main/docs
lint:
  cspellOptions:
    cspell:
      words:
        - katanomi
themeConfig:
  socialLinks:
    - icon: github
      mode: link
      content: https://github.com/alauda/doom
